Add Built In properties to entity list
builtinx/disconnect-tracking-protection pull request #1
Opened 2021-06-14 15:49 UTC by StummeJ

# What's changing 📝

This adds Built In's properties and resources to the entity list for companies that integrate the disconnect.me lists.  These are used to either aid in cross-domain cookies, or (if found abusive) blocks cross-domain cookies.  Currently, Firefox and Microsoft is using the disconnect.me entities list to allow sites that own multiple properties (domains) to treat their cross-domain cookies as 1st party cookies instead of 3rd party cookies.

## References 📓

https://docs.microsoft.com/en-us/microsoft-edge/web-platform/tracking-prevention#mitigations
https://github.com/mozilla-services/shavar-prod-lists#disconnect-entitylistjson

2021-06-14 18:58 UTC, cgundy approved these changes
Seems good to me. Could you describe a little more how this might impact the data team? Would we be able to attribute more cross-domain traffic after this change?

2021-06-14 18:59 UTC, StummeJ commented
@cgundy at least for Firefox and Microsoft we should be able to access `builtin.com` cookies on market sites.

2021-06-14 19:27 UTC, tomislavmitic2012 approved these changes

2021-06-14 19:37 UTC, cgundy commented
> @cgundy at least for Firefox and Microsoft we should be able to access `builtin.com` cookies on market sites. I think there are cookies for tracking right? otherwise, we might be able to start using a cookie to keep a common session, and for browsers that support this list, we can have another piece of data correlating things.

I think we use local storage for regular tracking and url state paremeters for cross-domain tracking. Brian put together some documentation https://confluence.builtin.com/display/DD/Cross+Domain+Sessions. I don't think we've specifically looked into whether our tracking is lower for certain browsers, but having these properties seems like a good idea!

2021-06-16 18:43 UTC, LeeAMitchell approved these changes

2021-06-16 18:54 UTC, aweiksnar requested changes
Just found a couple typos on the Seattle domains

2021-06-16 18:54 UTC, aweiksnar commented on entities.json
> +        "builtinseatlle.com",
Typo on this domain

```suggestion
        "builtinseattle.com",
```

2021-06-16 18:54 UTC, aweiksnar commented on entities.json
> +        "builtinseatlle.com",
Typo on this domain
```suggestion
        "builtinseattle.com",
```

2021-06-28 16:10 UTC, aweiksnar approved these changes

2021-06-28 16:22 UTC, merged